version: 2
jobs:
  build:
    docker:
          - image: circleci/golang:1.9

    working_directory: /go/src/github.com/andrisasuke/jsonull

    steps:
          - checkout
          - run: go get github.com/stretchr/testify
          - run: go get -v
          - run: go test ./... -v
          - run: go build -v
